INSERT INTO PHYSICAL_DATA (ID, WEIGHT, AGE, SIZE) VALUES (1, 75.0, 21, 1.87);
INSERT INTO USER (ID, PHYSICAL_DATA_ID, PSEUDO, PASSWORD) VALUES (1, 1, 'robin.camarasa', 'p8hmbk8!');

INSERT INTO PHYSICAL_DATA (ID, WEIGHT, AGE, SIZE) VALUES (2, 63.0, 21, 1.67);
INSERT INTO USER (ID, PHYSICAL_DATA_ID, PSEUDO, PASSWORD) VALUES (2, 2, 'mathilde.matly', 'onsenfiche');
